#!/usr/bin/env sh

#/*****************************************************************************\
# Changing permissions
#\............................................................................./
{
	chmod 700 ~/.config/libreoffice/4 &&
	chmod 600 ~/.config/libreoffice/4/user/registrymodifications.xcu
} || exit
