.TH TELEPORTER 1 2018\-11\-11
.nh
.SH НАЗВАНИЕ
teleporter \- скрипт для управления удалёнными подключениями и монтирования удалённых файловых систем
.SH СИНТАКСИС
\fBteleporter\fP [\fIопции\fP] ... [\fIимя_подключения_или_url\fP] [\fIаргументы\fP]

Формат URL: \fIпротокол\fP\fB://\fP[\fIпользователь\fP\fB@\fP]\fIхост\fP[\fB:\fP\fIпорт\fP][\fIпуть\fP]
.SH ПАРАМЕТРЫ
.TP
\fB\-l\fP
.RS
.TP
Выводит таблицу существующих подключений в следующем формате:
\fIстатус\fP \fIимя_подключения\fP
.TP
Поле "\fIстатус\fP" может принимать следующие значения:
.RS
.TP
\fB*\fP
несохранённое подключение
.TP
\fB+\fP
активное сохранённое подключение
.TP
\fB\-\fP
неактивное сохранённое подключение
.TP
\fB!\fP
файловая система недоступна
.RE
.RE
.TP
\fB\-u\fP
Отмонтировать файловую систему. Если файловая система не указана, будут отмонтированы все файловые системы.
.TP
\fB\-f\fP
Отмонтировать файловую систему, даже если она используется каким\-либо процессом
.TP
\fB\-i\fP \fIпуть\fP
Использовать указанный файл ключа аутентификации
.TP
\fB\-p\fP \fIпротокол\fP
Использовать указанный протокол вместо протокола по умолчанию
.TP
\fB\-o\fP \fIимя\fP\fB=\fP\fIзначение\fP
Переопределить значение опции конфигурации соединения. Может использоваться несколько раз.
.TP
\fB\-d\fP \fIпуть\fP
Использовать указанный путь к каталогу с файлами конфигурации
.TP
\fB\-a\fP
Примонтировать все файловые системы с указанной опцией automount
.TP
\fB\-v\fP, \fB\-\-version\fP
Показать версию и выйти
.TP
\fB\-h\fP, \fB\-\-help\fP
Показать справку и выйти
.SH ОКРУЖЕНИЕ
.TP
.B PASSWORD
Используется для автоматического ввода пароля. Пример:

\fBPASSWORD\fP=yourpassword teleporter sftp://root@storage.lan:2022/root
.SH ФАЙЛЫ
.TP
.I "~/.teleporter/conf"
Каталог, содержащий конфигурационные файлы подключений
.TP
.I "~/.teleporter/keys"
Каталог, содержащий ключи аутентификации
.TP
.I "~/.teleporter/mnt"
Каталог для точек монтирования
.SH "СМОТРИТЕ ТАКЖЕ"
.BR ssh (1),
.BR sshfs (1),
.BR ssh\-keygen (1),
.BR curlftpfs (1),
.BR smbnetfs (1),
.BR vncviewer (1),
.BR xfreerdp (1)
.SH АВТОРЫ
\fB10geek\fP
