#!/usr/bin/env sh

unset -v debconf_selections_locales
[ -z "$VARFILE" ] || . "$VARFILE" || exit


#/*****************************************************************************\
# Setting old debconf selections of the `locales` package and reconfiguring it
#\............................................................................./
[ -z "$debconf_selections_locales" ] || {
	debconf-set-selections <<- EOF &&
	$debconf_selections_locales
	EOF
	dpkg-reconfigure locales
} || exit
