#!/usr/bin/env sh

#/*****************************************************************************\
# Changing permissions
#\............................................................................./
chmod 700 "$PREPDIR/etc/debcomp/userconf/common/skel-root" || exit
